version: "3.8"
services:
  mongodb:
    image: mongo:4.4.1
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - net
volumes:
  mongodb-data:
networks:
  net:
